# Generated by Django 3.2.16 on 2022-10-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productsite',
            options={'verbose_name_plural': 'Product Sites'},
        ),
        migrations.AlterModelOptions(
            name='productsize',
            options={'verbose_name_plural': 'Product Sizes'},
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
